version: "3.2"
services:
  depends_on:
    - redis
  environment:
    - REDIS_HOST=redis
  db:
    image: postgres:9.4
    restart: always
    container_name: lastfmDB
    ports:
      - "5432:5432"
    networks:
      - pylast
    environment:
      POSTGRES_PASSWORD: "lastfm123"
      POSTGRES_DB: "playlist"
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    container_name:  pgadmin4_B
    environment:
      PGADMIN_DEFAULT_EMAIL: "lastfm@pylast.com"
      PGADMIN_DEFAULT_PASSWORD: "lastfm123"
    ports:
      - "80:80"
    links:
      - db
    networks:
      - pylast
    depends_on:
      - redis
  scrapper-lastfm:
    build: ./app
    container_name: lastfmScrapper
    links:
      - db
    networks:
      - pylast
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/Extraordinario
    command: ["python", "./scrapper.py"]
    depends_on:
     - redis
  app-lastfm:
    build: ./app
    container_name: lastfmApp
    restart: always
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - postgresql
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    command: ["python", "./applastfm.py"]
    depends_on:
      - scrapper-lastfm

  redis:
    image: redis:latest
    container_name: redis-docker
    ports:
      - 6379:6379
    volumes:
      - type: bind
        source: ./config/redis.conf
        target: /redis.conf
    command: ["redis-server", "/redis.conf"]
    networks:
      - pylast
    depends_on:
     - scrapper

