version: "3.3"

services: 
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
    ports:
      - "27017:27017"
  python:
    build: 
      context: ./ContenedorB/
    links:
      - "mongo"
    depends_on:
      - "mongo"
  flask-app:
    build:
      context:  ./ContenedorC/
    links:
      - "mongo"
    depends_on:
      - "mongo"
      - "python"
    ports:
      - "5000:5000"