version: "3.3"
services:
    mongodb:
        image: mongo:latest
        restart: always
        container_name: mongodb
        command: mongod --port 27018
        volumes:
            - .data/db:/data/db
        env_file:
            - '.env'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_HOSTNAME: ${MONGO_INITDB_HOSTNAME}
            MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
        ports:
            - "27018:27018"
        logging:
            driver: none
    python:
        build: 
            context: ./contenedor-b/.
        container_name: python
        links:
            - "mongodb"
        depends_on:
            - "mongodb"
        env_file:
            - '.env'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_HOSTNAME: ${MONGO_INITDB_HOSTNAME}
            MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}
    flask:
        build:
            context: ./contenedor-c/.
        ports:
            - "5000:5000"
        links:
            - "mongodb"
        depends_on:
            - "python"
        env_file:
            - '.env'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_HOSTNAME: ${MONGO_INITDB_HOSTNAME}
            MONGO_INITDB_PORT: ${MONGO_INITDB_PORT}