version: "3"

services: 
    app:
        image: deolara/breakinfcharacters
        ports: 
            - '5050'
        links: 
            - db
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_USER: admin1
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - ./db:/docker-entrypoint-initdb.d/:ro
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: breaking-myadmin
        environment:
          MYSQL_ROOT_PASSWORD: root
          PMA_HOST: db
          PMA_PORT: 3306
          PMA_ARBITRARY: 1
        restart: always
        ports:
          - 8088:80
        links: 
            - db
    