version: "3.3"

services: 
  mongo:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - "27017:27017"
    volumes: 
      - .data/db:/data/db
  python:
      build: 
        context: ./B_Container/
      container_name: python_scraper
      links: 
        - "mongo"
      depends_on: 
        - "mongo"
  flask:
      build: 
        context: ./C_Container/
      ports: 
        - "5000:5000"
      links: 
        - "mongo"
      depends_on: 
        - "python"