version: "3.7"

services:
  # CONTAINER A - MONGO DB
  db:
    image: mongo

  # CONTAINER B - REQUESTS
  users:
    build: "./reqs"
    environment:
      - "NUM_USERS=10"

  # CONTAINER C - VIEWER
  viewer:
    build: "./view"
    ports:
      - "80:5000"
    environment:
      - "FLASK_APP=view.py"

  # CONTAINER TEST
  # phpmoadmin:
  #  image: "thinkcube/phpmoadmin"
  #  ports:
  #    - "8080:80"