version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=users"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=david@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=12345"
      - "PGADMIN_LISTEN_PORT=8080"

  scrapper:
    build: .


  
