version: "3.8"
services:
  # app:
  #   build: ./app
  #   container_name: pyapp
  #   restart: always
  #   links:
  #     - db
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - custom
  #   volumes:
  #     - type: bind
  #       source: ./app
  #       target: /usr/src/app
  #   depends_on:
  #    - scraper

  # scraper:
  #   build: ./scraper
  #   container_name: pyscrape
  #   links: 
  #     - db
  #   networks:
  #     - custom
  #   volumes:
  #     - type: bind
  #       source: ./scraper
  #       target: /usr/src/app
  #   depends_on:
  #    - db

  db:
    image: postgres:12.2
    restart: always
    container_name: postgreDB
    ports:
      - "5432:5432"
    networks:
      - custom
    environment:
      POSTGRES_DB: "random_cats"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "secret123"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: postgreAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@test.com"
      PGADMIN_DEFAULT_PASSWORD: "othersecret123"
      PGADMIN_LISTEN_PORT: "80"
    ports:
     - "8080:80"
    links:
     - db
    networks:
      - custom
    depends_on:
     - db

volumes:
  db-data:
  pgadmin-data:

networks:
  custom:
    driver: bridge