version: "3.3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - "POSTGRES_DB=postgres_db"
      - "POSTGRES_PASSWORD=sudovon"
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    links:
      - "postgres"
    depends_on:
      - "postgres"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=sudo@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=sudovon"
      - "PGADMIN_LISTEN_PORT=8080"
    ports:
      - "8080:8080"
    networks:
      - postgres
  python:
    container_name: python
    build:
      context: .
    links:
      - "postgres"
    depends_on:
      - "postgres"
    networks:
      - postgres
networks:
  postgres:
      driver: bridge