version: '2'
services:
        generador:
                container_name: generador
                build: ./app
                networks:
                        - ejercicio8
                command: ["generador.py"]
                depends_on:
                        - mongodb
        mongodb:
                image: mongo
                container_name: mongodb
                restart: always
                environment:
                        MONGO_INITDB_ROOT_USERNAME: generador
                        MONGO_INITDB_ROOT_PASSWORD: generador
                volumes:
                                - ./volumes/mongodb:/volumes/mongodb        
                ports:
                        - 27017:27017
                networks:
                        - ejercicio8
        redisdb:

                image: redis:latest
                container_name: redis_db
                ports:
                        - 6379:6379
                volumes:
                        - ./config/redis.conf:/redis.conf
                command: ["redis-server", "/redis.conf"]
                networks:
                        - ejercicio8
                depends_on:
                        - generador

networks:
        ejercicio8:
                driver: bridge

