version: "3.2"
services:
  script:
    build: ./app_script
    container_name: contenedor_2
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./app_script
        target: /usr/src/DAS_Pract3
    command: ["python", "./app.py"]

  redis:
    image: redis:latest
    container_name: contenedor_1
    ports:
      - 6381:6379
    volumes:
      - type: bind
        source: ./config/redis.conf
        target: /redis.conf
    command: ["redis-server", "/redis.conf"]
