version: "3.2"
services:
  script:
    build: ./app
    container_name: redis_script
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
    - type: bind
      source: ./app
      target: /home/salguer/proyects
    command: ["python", "./inserts.py"]

  redis:
    image: redis:latest
    container_name: redis-docker
    ports:
      - 6380:6379
    volumes:
      - type: bind
        source: ./config/redis.conf
        target: /redis.conf
    command: ["redis-server", "/redis.conf"]


